#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Feb 23 17:24:37 CST 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 808e0af0b6204971af911e88d1a0f46a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot myReplicatorTEST_behav xil_defaultlib.myReplicatorTEST xil_defaultlib.glbl -log elaborate.log"
xelab -wto 808e0af0b6204971af911e88d1a0f46a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot myReplicatorTEST_behav xil_defaultlib.myReplicatorTEST xil_defaultlib.glbl -log elaborate.log

